# "bash gd.sh gd"  = drive-server-side-across-configs
# "bash od.sh gd"  = normal copy

name: 同步作業
on:
    push:
    schedule:
        - cron: '0 0/6 * * *'
jobs:
    od_move:
        name: 同步操作
        runs-on: ubuntu-latest
        steps:
        - name: 檢查
          uses: actions/checkout@master
        - name: 下載並安裝 rclone
          run: #sudo curl https://rclone.org/install.sh | sudo bash
        - name: 解碼 config
          run: |
              # bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        - name: 開始操作
          run: |
              #bash od.sh
          env:
              DRIVE_SOURCE:   ${{ secrets.TEMPSCR }}
              DRIVE_TARGET:   ${{ secrets.TEMPTAR }}